### ISSUE TITLE
单卡下以ResNet50为基准的训练计划

### ISSUE THREAD

**Issue by rentainhe** [Oneflow-Inc/vision#205]
### TODO List
- [ ] 迁移一份Clean版本的ResNet50代码，跑通Eager，Graph的训练
- [ ] 调试到单卡下符合标准的精度（可以以CIFAR100为基础先进行调试，单卡ImageNet过于久了）
- [ ] 添加各种优化选项（阶段二），达到更高的加速比
